openapi: 3.2.0
info:
  title: 'Mealie Households: Webhooks API'
  description: '

    Mealie is a web application for managing your recipes, meal plans, and shopping lists. This is the Restful

    API interactive documentation that can be used to explore the API. If you''re justing getting started with

    the API and want to get started quickly, you can use the

    [API Usage | Mealie Docs](https://docs.mealie.io/documentation/getting-started/api-usage/)

    as a reference for how to get started.



    If you have any questions or comments about mealie, please use the discord server to talk to the developers or other

    community members. If you''d like to file an issue, please use the

    [GitHub Issue Tracker | Mealie](https://github.com/mealie-recipes/mealie/issues/new/choose)



    ## Helpful Links

    - [Home Page](https://mealie.io)

    - [Documentation](https://docs.mealie.io)

    - [Discord](https://discord.gg/QuStdQGSGK)

    - [Demo](https://demo.mealie.io)

    '
  version: nightly
tags:
- name: 'Households: Webhooks'
paths:
  /api/households/webhooks:
    get:
      tags:
      - 'Households: Webhooks'
      summary: Get All
      operationId: get_all_api_households_webhooks_get
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: orderBy
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Orderby
      - name: orderByNullPosition
        in: query
        required: false
        schema:
          anyOf:
          - $ref: '#/components/schemas/OrderByNullPosition'
          - type: 'null'
          title: Orderbynullposition
      - name: orderDirection
        in: query
        required: false
        schema:
          $ref: '#/components/schemas/OrderDirection'
          default: desc
      - name: queryFilter
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Queryfilter
      - name: paginationSeed
        in: query
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Paginationseed
      - name: page
        in: query
        required: false
        schema:
          type: integer
          default: 1
          title: Page
      - name: perPage
        in: query
        required: false
        schema:
          type: integer
          default: 50
          title: Perpage
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookPagination'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - 'Households: Webhooks'
      summary: Create One
      operationId: create_one_api_households_webhooks_post
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhook'
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadWebhook'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/households/webhooks/rerun:
    post:
      tags:
      - 'Households: Webhooks'
      summary: Rerun Webhooks
      description: Manually re-fires all previously scheduled webhooks for today
      operationId: rerun_webhooks_api_households_webhooks_rerun_post
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/households/webhooks/{item_id}:
    get:
      tags:
      - 'Households: Webhooks'
      summary: Get One
      operationId: get_one_api_households_webhooks__item_id__get
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          format: uuid4
          title: Item Id
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadWebhook'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - 'Households: Webhooks'
      summary: Update One
      operationId: update_one_api_households_webhooks__item_id__put
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          format: uuid4
          title: Item Id
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhook'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadWebhook'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - 'Households: Webhooks'
      summary: Delete One
      operationId: delete_one_api_households_webhooks__item_id__delete
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          format: uuid4
          title: Item Id
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadWebhook'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/households/webhooks/{item_id}/test:
    post:
      tags:
      - 'Households: Webhooks'
      summary: Test One
      operationId: test_one_api_households_webhooks__item_id__test_post
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: item_id
        in: path
        required: true
        schema:
          type: string
          format: uuid4
          title: Item Id
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ReadWebhook:
      properties:
        enabled:
          type: boolean
          title: Enabled
          default: true
        name:
          type: string
          title: Name
          default: ''
        url:
          type: string
          title: Url
          default: ''
        webhookType:
          $ref: '#/components/schemas/WebhookType'
          default: mealplan
        scheduledTime:
          type: string
          format: time
          title: Scheduledtime
        groupId:
          type: string
          format: uuid4
          title: Groupid
        householdId:
          type: string
          format: uuid4
          title: Householdid
        id:
          type: string
          format: uuid4
          title: Id
      type: object
      required:
      - scheduledTime
      - groupId
      - householdId
      - id
      title: ReadWebhook
    WebhookPagination:
      properties:
        page:
          type: integer
          title: Page
          default: 1
        per_page:
          type: integer
          title: Per Page
          default: 10
        total:
          type: integer
          title: Total
          default: 0
        total_pages:
          type: integer
          title: Total Pages
          default: 0
        items:
          items:
            $ref: '#/components/schemas/ReadWebhook'
          type: array
          title: Items
        next:
          anyOf:
          - type: string
          - type: 'null'
          title: Next
        previous:
          anyOf:
          - type: string
          - type: 'null'
          title: Previous
      type: object
      required:
      - items
      title: WebhookPagination
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    OrderDirection:
      type: string
      enum:
      - asc
      - desc
      title: OrderDirection
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    OrderByNullPosition:
      type: string
      enum:
      - first
      - last
      title: OrderByNullPosition
    CreateWebhook:
      properties:
        enabled:
          type: boolean
          title: Enabled
          default: true
        name:
          type: string
          title: Name
          default: ''
        url:
          type: string
          title: Url
          default: ''
        webhookType:
          $ref: '#/components/schemas/WebhookType'
          default: mealplan
        scheduledTime:
          type: string
          format: time
          title: Scheduledtime
      type: object
      required:
      - scheduledTime
      title: CreateWebhook
    WebhookType:
      type: string
      enum:
      - mealplan
      title: WebhookType
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /api/auth/token
