openapi: 3.2.0
info:
  title: 'Mealie Groups: Migrations API'
  description: '

    Mealie is a web application for managing your recipes, meal plans, and shopping lists. This is the Restful

    API interactive documentation that can be used to explore the API. If you''re justing getting started with

    the API and want to get started quickly, you can use the

    [API Usage | Mealie Docs](https://docs.mealie.io/documentation/getting-started/api-usage/)

    as a reference for how to get started.



    If you have any questions or comments about mealie, please use the discord server to talk to the developers or other

    community members. If you''d like to file an issue, please use the

    [GitHub Issue Tracker | Mealie](https://github.com/mealie-recipes/mealie/issues/new/choose)



    ## Helpful Links

    - [Home Page](https://mealie.io)

    - [Documentation](https://docs.mealie.io)

    - [Discord](https://discord.gg/QuStdQGSGK)

    - [Demo](https://demo.mealie.io)

    '
  version: nightly
tags:
- name: 'Groups: Migrations'
paths:
  /api/groups/migrations:
    post:
      tags:
      - 'Groups: Migrations'
      summary: Start Data Migration
      operationId: start_data_migration_api_groups_migrations_post
      security:
      - OAuth2PasswordBearer: []
      parameters:
      - name: accept-language
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Accept-Language
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Body_start_data_migration_api_groups_migrations_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportSummary'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    SupportedMigrations:
      type: string
      enum:
      - nextcloud
      - chowdown
      - copymethat
      - paprika
      - mealie_alpha
      - tandoor
      - plantoeat
      - myrecipebox
      - recipekeeper
      - cookn
      title: SupportedMigrations
    Body_start_data_migration_api_groups_migrations_post:
      properties:
        add_migration_tag:
          type: boolean
          title: Add Migration Tag
          default: false
        migration_type:
          $ref: '#/components/schemas/SupportedMigrations'
        archive:
          type: string
          contentMediaType: application/octet-stream
          title: Archive
      type: object
      required:
      - migration_type
      - archive
      title: Body_start_data_migration_api_groups_migrations_post
    ReportSummaryStatus:
      type: string
      enum:
      - in-progress
      - success
      - failure
      - partial
      title: ReportSummaryStatus
    ReportCategory:
      type: string
      enum:
      - backup
      - restore
      - migration
      - bulk_import
      title: ReportCategory
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ReportSummary:
      properties:
        timestamp:
          type: string
          format: date-time
          title: Timestamp
        category:
          $ref: '#/components/schemas/ReportCategory'
        groupId:
          type: string
          format: uuid4
          title: Groupid
        name:
          type: string
          title: Name
        status:
          $ref: '#/components/schemas/ReportSummaryStatus'
          default: in-progress
        id:
          type: string
          format: uuid4
          title: Id
      type: object
      required:
      - category
      - groupId
      - name
      - id
      title: ReportSummary
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /api/auth/token
